appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dZxjMM37GGb9MItarr+Vw1/0tmIwVW/zMBWqxR+OXvnaF9hbOHF3rJ1m+1s6O3fJXHuyemucsTgFjde5Gq0bTUUAO8Trd8yo6LOczWGIh2uiz4PW7k7GYpwLeEOrjf0U2x+syfGWEtltNUXOmaVrH7kHnaVcMeZDRdWXP0qFGCGcrtbruXvzViudM1yIBud7r9c2s1jaZmQveUC8YzNyIQzKxbXmFE08sddKisU7RX0eHGloF67qNWtxxm6wtbDzqxxstILTMHbB68CUWB/95CqEXJ/yq4M1PYhc+dQZtIUtz2GuDjHWMhCwrjIlV5sxa+ED2zf47/e/r53tkHXXG9c6uvqARgVikb+YK5/hP88vKPQCFYioeP8WRgb5u7hKR/sCF0y+LS7CoQ7hD4HY738SLqPOjOsVMLSvl/BdXxRQWacWs9EJm9akvdb1eGsdGeNV5bYciYbL0m5RmoF67ZUC5fS5KZSXSPREe3DLrXGluGlkfVoN6i9pWruQK6TLOkXJFzWVq1Y9NXxhM4RP9YkkW2JMUmBdQ1W72WkVRVyotdVen6elRLMTaYndStCU/CUg7To7NXrPI3fXEA2D49/xt0Ixc+2JtDpIWij81+u3ivBp+ts0q529F9zE/p7uutJsE0sanIpPOgVln7CMeiSKUL9d5fcHzJqX6yWkbrk=}
