travis:
  secure:
    BINSTAR_TOKEN: M0LKzad+mjumL+vJNk9NLVnty5I4pd/kfJVRefaq1nLZk8ZO4XrKUbfekEJRWyUfQsQJ7jFWkyAoVJyX83l2iIlKxsed6iZrIbPKXZKVhIYOtqiXjoqDlIxRntcgSqGHZfPZXIyWWC46CYFa1ibAT+TiUltzaVZrdR2vENlY3po6JWf1eYu9G1QvA/ct2fTXzP74kt5xM/2nsOWA8lOl0WVde8A8vFZ99XGmr3jMm9/GJJcPCaLaJp2cnFCvMp41F9Wff8WIyqPANjaA+5UZwrozSPkwWov4EeMDMbuEgZNz1N59HMhfP+GRPRwuIwL/TBjafC5DEt5u6eCYyQEM8MGllkUL4Ebuu/YHoUgXvf2bMj6AgHSbyCyTB+RtawzVvEOAc+cYO/MLvhgW9DZZpXlljLvkkuytr5789oHRoWeAFAC2um+wYQs8cK8cap24Yg4qlQ5mhxfT3AfZSgvrqy5gW/qQ70F/67CtEin3J1BHhsRAS3u1oDnCQPvYSdmb4VqR/fG9r8oixvywI5XvFDFlWSJqqeAX6TrFobAiAP/qpOHI6EJssiouEuldSrrtpKMTn72Tepz2l3/e8uotvykC0SlwC0GGJqVcf2DJI19mptOdsdteQHVpheKT4KOEcafug9ndd5IeOVllAch8AAyqIkfkr5vbvovEp0UMG9o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
